#!/usr/bin/env python3
"""Convert an image (BMP/PNG/...) into a Dreamcast VMU save icon C header.

VMU icons are 32x32 pixels, 4bpp with a 16-entry ARGB4444 palette. The input
image is resized to 32x32 if needed and quantized down to 16 colors (15 when
the image has transparency; fully transparent pixels get a dedicated A=0
palette entry).

Usage:
    tools/png2vmuicon.py icon.bmp src/dc_vmu_icon.h
"""

import sys

from PIL import Image


def argb4444(r, g, b, a=255):
    return ((a >> 4) << 12) | ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]

    im = Image.open(src).convert("RGBA")
    if im.size != (32, 32):
        print(f"NOTE: resizing {im.size[0]}x{im.size[1]} -> 32x32")
        im = im.resize((32, 32), Image.LANCZOS)

    alpha = im.getchannel("A")
    has_transparency = alpha.getextrema()[0] < 128
    max_colors = 15 if has_transparency else 16

    # Quantize the opaque pixels; PIL's median cut needs a P-mode detour.
    rgb = im.convert("RGB")
    quant = rgb.quantize(colors=max_colors, method=Image.Quantize.MEDIANCUT)
    pal = quant.getpalette()[: max_colors * 3]

    palette = []
    if has_transparency:
        palette.append(0x0000)  # entry 0: fully transparent
    for i in range(max_colors):
        r, g, b = pal[i * 3 : i * 3 + 3]
        palette.append(argb4444(r, g, b))
    while len(palette) < 16:
        palette.append(0x0000)

    indices = []
    quant_px = quant.load()
    alpha_px = alpha.load()
    offset = 1 if has_transparency else 0
    for y in range(32):
        for x in range(32):
            if has_transparency and alpha_px[x, y] < 128:
                indices.append(0)
            else:
                indices.append(quant_px[x, y] + offset)

    # Two pixels per byte, high nibble = left pixel
    data = bytearray()
    for i in range(0, len(indices), 2):
        data.append((indices[i] << 4) | indices[i + 1])
    assert len(data) == 512

    with open(dst, "w") as f:
        f.write("// Generated by tools/png2vmuicon.py from " + src.split("/")[-1] + " - do not edit\n")
        f.write("// 32x32 VMU save icon: 16-entry ARGB4444 palette + 4bpp pixel data\n\n")
        f.write("static const u16 dc_vmu_icon_pal[16] = {\n    ")
        f.write(", ".join(f"0x{c:04X}" for c in palette))
        f.write("\n};\n\n")
        f.write("static const u8 dc_vmu_icon_data[512] = {\n")
        for i in range(0, 512, 16):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in data[i : i + 16]) + ",\n")
        f.write("};\n")
    print(f"Wrote {dst} ({len(set(indices))} colors used)")


if __name__ == "__main__":
    main()
